[project]
name = "macro"
version = "1.0.0-beta+001"
authors = [
    {name = "Tom Scheeper", email = "tomscheeper@gmail.com"},
    ]

dependencies = [
    "grienetsiis @ git+https://github.com/ButerBreaGrieneTsiis/grienetsiis.git@v2.0.0-rc5",
]
