[project]
name = "macro"
version = "1.0.0-dev"
authors = [
    {name = "Tom Scheeper", email = "tomscheeper@gmail.com"},
    ]

dependencies = [
    "grienetsiis @ git+https://github.com/ButerBreaGrieneTsiis/grienetsiis.git@v1.4.6",
]
